# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

project_name = "boilerplate"
scheme = project_name
path = "./#{project_name}.xcodeproj"

platform :ios do
  desc "Build simulator app for Detox"
  lane :sim do
    gym
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "boilerplate.xcodeproj")
    build_app(workspace: "boilerplate.xcworkspace", scheme: scheme)
    groups = ENV["PILOT_GROUPS"]
    upload_to_testflight(distribute_external: true, groups: groups)
  end

end
